### ISSUE TITLE
latexcheck crashes instantly 

### ISSUE THREAD

**Issue by dseddah** [dainiak/latexcheck-py#1]
Hi,
latexcheck crashes instantly when I run it. Just installed with pip install as required, running 

Python 3.10.9
conda 22.11.1

command: 
 latexcheck Intro.tex

output: 

Traceback (most recent call last):
  File "/Users/djame2/miniforge3M1real/bin/latexcheck", line 5, in <module>
    from latexcheck import main
  File "/Users/djame2/miniforge3M1real/lib/python3.10/site-packages/latexcheck/__init__.py", line 586
    print(f'{key}:\n    {"\n    ".join(repr(source[max(0, t-10):t+20]) for t in value)}')
                                                                                        ^
SyntaxError: f-string expression part cannot include a backslash

Best,
Djamé

**Comment by dainiak** [comment]
Thank you for the information @dseddah  !
It was due to that the code was written with Python 3.11 in mind, while I have marked a lower Python version in the release. Fixed that.
